name: mallxx_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^1.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  fluttertoast: ^8.0.8
  flutter_easyrefresh: ^2.2.1
  # shared_preferences: ^2.0.6
  flutter_swiper_null_safety: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  flutter_screenutil: ^5.0.4
  flutter_html: ^2.2.1
  photo_view: ^0.13.0
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.12
  icon_badge: ^1.0.0

  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
      - assets/images/
      - assets/icons/

